export const ServerEvents = {
  EXECUTE: 'EXECUTE',
  UPDATE_VERSIONS: 'UPDATE_VERSIONS',
  SELECT_VERSION: 'SELECT_VERSION',
};

export const ClientEvents = {
  TYRANT_EVENT: 'TYRANT_EVENT',
  VERSION_MANAGER_STATE_CHANGE: 'VERSION_MANAGER_STATE_CHANGE',
};
