export const Events = {
  STARTED_EXECUTION: 'STARTED_EXECUTION',
  FINISHED_EXECUTION: 'FINISHED_EXECUTION',
  LOG: 'LOG',
  WRITE: 'WRITE',
  TICK: 'TICK',
  STARTED_RUNNING: 'STARTED_RUNNING',
  RERUNNING_TESTS: 'RERUNNING_TESTS',
};
